language: python
python:
  - "2.7"

# install required packages
before_install:
 - sudo apt-get install -qq devscripts
 - sudo apt-get install -qq python-support
 - sudo apt-get install -qq python-mock

# install dependencies
install:
  - pip install -r requirements.txt

# run 
script:
  - make version
  - cat version.txt
  - make test
  - make deb

# setup notifications
notifications:
  email: false
