language: python
python:
  - "2.6"
  - "2.7"

# install required packages
before_install:
 - sudo apt-get install -qq devscripts
 - sudo apt-get install -qq python-support
 - sudo apt-get install -qq python-mock


# install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"

# run 
script: make deb

# setup notifications
notifications:
  email: false
